create database student;
use student;
create table details(ID int,Name varchar(20),Address Varchar(20),Maths int,Science int,Physics int,total int);
insert into details values(1,'Arun','Salem',50,50,50,150);
insert into details values(2,'Ajin','Kozhikode',60,60,60,180);
insert into details values(3,'Bala','Salem',70,70,70,210);
insert into details values(4,'Steve','Korea',80,80,80,240);
insert into details values(5,'Sarang','Kozhikode',90,90,90,270);
insert into details values(6,'Varun','Malappuram',40,40,35,115);
insert into details values(7,'Rima','Kannur',100,100,80,280);
insert into details values(8,'Tony','NewYork',50,50,80,180);
select * from details;
select ID,Name from details;
select ID,Name from details where total>250;
select * from details where Address='Kozhikode';
update details set total=250 where Name = 'Varun';
delete from details where Name='Sarang';
select total,Name from details where Name='Rima' and total is not null;
update details set Name='Robin' where Name='Tony';
select * from details where Address='Kozhikode' or Address='Korea';
alter table details add Department varchar(20);
update details set Department='MCA' where ID=1;
update details set Department='MECH' where ID=2;
update details set Department='B-Tech' where ID=3;
update details set Department='MCA' where ID=4;
update details set Department='Civil' where ID=6;
update details set Department='EEE' where ID=7;
update details set Department='MCA' where ID=8;
select Name,Department from details order by Name desc;
select Name,Address from details where Address is NULL;
select max(total) from details;
select min(total) from details;
select avg(Science) from details;
select sum(Physics) from details;
select Name,Department from details where Department like '%A';
select Name from details where Name like 'A%';
alter table details drop total;
alter table details add total int; 
update details set total=150 where ID='1';
update details set total=180 where ID='2';
update details set total=210 where ID='3';
update details set total=240 where ID='4';
update details set total=115 where ID='6';
update details set total=280 where ID='7';
update details set total=180 where ID='8';
select*from details;
alter table details add Age int;
update details set Age=22 where ID=1;
update details set Age=23 where ID=2;
update details set Age=21 where ID=3;
update details set Age=29 where ID=4;
update details set Age=26 where ID=6;
update details set Age=15 where ID=7;
update details set Age=30 where ID=8;
alter table details add constraint chk_Age check(Age>=45);
alter table details drop constraint chk_Age;
create view student as select ID,Name,total from details where Department='MCA';
select*from student;
drop view student;
delete from details where Age=26;
commit;
select*from details;
delete from details where Age=30;
rollback;
savepoint sp1;
update details set Age=20 where Age=22;
rollback to sp1;
release sp1;
select * from details where total=(select max(total)from details);
alter table details add Add_No int;
update details set Add_No=1001 where  ID=1;
update details set Add_No=1002 where  ID=2;
update details set Add_No=1003 where  ID=3;
update details set Add_No=1004 where  ID=4;
update details set Add_No=1007 where  ID=7;
alter table details modify Name varchar(20) not null;
alter table details modify Add_NO int not null;
describe details;
select*from details;
alter table details add email varchar(50);

update details set email='arun@gamil.com' where ID=1;
update details set email='ajin@gamil.com' where ID=2;
update details set email='bala@gamil.com' where ID=3;
update details set email='steve@gamil.com' where ID=4;
update details set email='rima@gamil.com' where ID=7;
alter table details add constraint em_uni unique(email);
create table Department(Dept_id int,Dept_name varchar(20),Location_id int);
insert into Department values(12,'MCA',113);
insert into Department values(13,'Civil',103);
insert into Department values(14,'Mech',193);
insert into Department values(15,'EEE',180);
insert into Department values(16,'B-tech',153);
select*from Department;
alter table Department add constraint Dept_id_pk
primary key(Dept_id);
describe Department;
select ID,Department from details union select Dept_id,Dept_name from Department;
select distinct Department from details;